steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - europe-north1-docker.pkg.dev/taavi-bot/taavi
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-north1-docker.pkg.dev/taavi-bot/taavi
