version: '3'

services:
  database:
    image: timescale/timescaledb:latest-pg13
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ${DB_DATA}:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    expose:
      - ${PORT}
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./users.ini:/app/users.ini
